-- 2022년 1월의 도서 판매 데이터
-- 저자 별 , 카테고리 별 TOTAL_SALES = A.PRICE * C.SALES

SELECT B.AUTHOR_ID, B.AUTHOR_NAME, A.CATEGORY, SUM(A.PRICE * C.SALES) AS TOTAL_SALES
FROM BOOK AS A JOIN AUTHOR AS B ON A.AUTHOR_ID = B.AUTHOR_ID
               JOIN BOOK_SALES AS C ON A.BOOK_ID = C.BOOK_ID
WHERE YEAR(C.SALES_DATE) = 2022 AND MONTH(C.SALES_DATE) = 1
GROUP BY B.AUTHOR_ID, A.CATEGORY
ORDER BY 1, 3 DESC