-- 여자: Intact -> Spayed
-- 남자: Intact -> Neutered

SELECT B.ANIMAL_ID, B.ANIMAL_TYPE, B.NAME
FROM ANIMAL_INS AS A JOIN ANIMAL_OUTS AS B ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE A.SEX_UPON_INTAKE LIKE 'Intact%' AND B.SEX_UPON_OUTCOME IN ('Spayed Female', 'Neutered Male')
ORDER BY B.ANIMAL_ID, B.ANIMAL_TYPE, B.ANIMAL_ID