-- 2021년 가입한 회원 중 상품 구매 회원수
-- 상품 구매 회원 비율 (2021년 가입한 회원 중 상품 구매 회원수 / 2021년 가입 회원)
WITH TMP AS (SELECT *
            FROM USER_INFO
            WHERE YEAR(JOINED) = 2021)

SELECT YEAR(B.SALES_DATE) AS YEAR, MONTH(B.SALES_DATE) AS MONTH, COUNT(DISTINCT A.USER_ID) AS PURCHASED_USERS, ROUND(COUNT(DISTINCT A.USER_ID) / (SELECT COUNT(*) FROM TMP), 1) AS PUCHASED_RATIO
FROM USER_INFO AS A LEFT JOIN ONLINE_SALE AS B ON A.USER_ID = B.USER_ID
WHERE YEAR(A.JOINED) = 2021 AND B.ONLINE_SALE_ID IS NOT NULL
GROUP BY 1, 2
ORDER BY 1, 2