WITH A AS (SELECT H.HISTORY_ID, C.DAILY_FEE
            , DATEDIFF(H.END_DATE, H.START_DATE)+1 AS 'RENTAL_DAYS' # FEE계산을 위한 렌탈 기간 구하기
            , CASE WHEN DATEDIFF(H.END_DATE, H.START_DATE)+1 >= 90 THEN '90일 이상'
            WHEN DATEDIFF(H.END_DATE, H.START_DATE)+1 >= 30 THEN '30일 이상'
            WHEN DATEDIFF(H.END_DATE, H.START_DATE)+1 >= 7 THEN '7일 이상'
            ELSE '7일 이하' END DURATION_TYPE # CAR_RENTAL_COMPANY_DISCOUNT_PLAN과 join하기 위함 
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
            JOIN CAR_RENTAL_COMPANY_CAR C ON C.CAR_ID = H.CAR_ID
        WHERE CAR_TYPE = '트럭')

SELECT A.HISTORY_ID
    , IF(B.DURATION_TYPE IS NULL, A.DAILY_FEE * A.RENTAL_DAYS, ROUND((A.DAILY_FEE * (100-B.DISCOUNT_RATE)*0.01) * A.RENTAL_DAYS,0)) AS 'FEE'
FROM A
LEFT JOIN (SELECT * FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE='트럭') B ON A.DURATION_TYPE = B.DURATION_TYPE
ORDER BY FEE DESC, HISTORY_ID DESC